### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-bib-py#6]
Originally all [`to_hash`](https://github.com/relaton/relaton-bib/search?q=to_hash) methods were skipped with the hope that [`dataclasses.asdict`](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict)

But because we need to keep YAML structure the same as original `relaton-bib` gem we need to port `to_hash` methods also and fix unit tests

 - https://github.com/relaton/relaton-bib/blob/master/lib/relaton_bib/hash_converter.rb

Also per https://stackoverflow.com/questions/52229521/why-is-dataclasses-asdictobj-10x-slower-than-obj-dict `dataclasses.asdict` is very slow

 - [ ] make sure that it support https://github.com/ietf-ribose/relaton-data-ieee/blob/main/data/IEC_62531.2012_REDLINE.yaml

**Comment by CAMOBAP** [comment]
in progress

**Comment by CAMOBAP** [comment]
was paused because other tasts, started work on it again

**Comment by CAMOBAP** [comment]
TODO make sure that dict are valid according to https://github.com/relaton/relaton-bib-py/issues/8#issuecomment-974162357 comment

**Comment by CAMOBAP** [comment]
Status:
 - [x] yml -> bibitem
 - [ ] bibitem -> yml

**Comment by CAMOBAP** [comment]
Looks like IETF project moved to far, @ronaldtse @strogonoff, are we still need this library?

**Comment by ronaldtse** [comment]
@CAMOBAP I believe @strogonoff has integrated code from this library into https://github.com/relaton/relaton-py which is in use in the bibxml-service. Can you help check relaton-py? Thanks.

**Comment by CAMOBAP** [comment]
Probably he did it from scratch but it looks really good & clean. I'm not sure if all entities from https://github.com/relaton/relaton-models but anyway it's working

Probably make sense to deprecate this repo

**Comment by strogonoff** [comment]
@CAMOBAP

It might be that some features from relaton-bib-py will need to be ported to relaton-py—we’ll see! There’s a chance @stefanomunarini will take charge of maintaining Relaton bindings in Python and look into consolidating this with relaton-py.
