### ISSUE TITLE
Check it support Legacy IETF BibXML

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-bib-py#8]
- [x] check how we can support IETF-flavored BibXML

**Comment by strogonoff** [comment]
According to https://github.com/relaton/relaton-bib#create-bibliographic-item-from-bibxml, relation-bib library supported parsing BibXML, but not necessarily IETF-flavored BibXML

**Comment by ronaldtse** [comment]
BibXML is only IETF-flavored, though... Maybe @andrew2net could answer.

**Comment by strogonoff** [comment]
> BibXML is only IETF-flavored, though... Maybe @andrew2net could answer.

That’d be great. I thought @CAMOBAP mentioned that the original `relaton-bib` implementation has an extra separate component responsible for IETF-flavored BibXML. Maybe I’m mistaken as to its purpose.

**Comment by andrew2net** [comment]
> BibXML is only IETF-flavored, though... Maybe @andrew2net could answer.

It was implemented in the relaton-ietf but since we need other flavor gems to handle BibXML I've moved it to relaton-bib. All flavor gems require relaton-bib so they can use BibXML parser and render.

**Comment by CAMOBAP** [comment]
@andrew2net thanks for the explanation, This means that `relaton-bib-py` will handle IETF BibXML too, because `relaton-bib` do this

@andrew2net just to complete the picture `relaton-bib` also supports BibTeX, 
1. where is this functionality used? 
1. As far as I understand BibXML and BibTeX it's the same BibItem but in different representation, is that true?

**Comment by andrew2net** [comment]
> @andrew2net just to complete the picture `relaton-bib` also supports BibTeX,
> 
> 1. where is this functionality used?

I don't know. There was a task to implement it so I just did it. Let's ask @ronaldtse 

> 2. As far as I understand BibXML and BibTeX it's the same BibItem but in different representation, is that true?

BibXML and BibTeX are different serializations of BibliographicItem. Keep in mind that these formats don't allow to save all BibliographicItem's attributes. So some attributes will be lost if we save a BibliographicItem in these formats.
YAML and RelatonXML keep all BibliographicItem's attributes but flavor gems need to use `.to_xml bibdata: true` to serialize flavor's attributes.

**Comment by strogonoff** [comment]
@andrew2net do you know if converting an IETF BibXML to Relaton (BibliographicItem) representation covers source BibXML properties fully? I.e. no data loss.

**Comment by andrew2net** [comment]
@strogonoff I did my best to implement a `<front>` element from the [rfc7991](https://datatracker.ietf.org/doc/html/rfc7991#section-2.26) specification but I didn't implement deprecated elements. So maybe old documents won't be parsed correctly.
I didn't find real documents that contain all metadata described in the specification to test the functionality. I created a fake document for test purposes but I'm not 100% sure if it is correct. So if you find any issue please let me know.

**Comment by ronaldtse** [comment]
> @CAMOBAP: `relaton-bib` also supports BibTeX

The intention is to allow Relaton to import from BibTeX and also write to BibTeX.

The BibTeX model is quite different from Relaton's.

> @strogonoff : converting an IETF BibXML to Relaton (BibliographicItem) representation covers source BibXML properties fully

I'm pretty sure we cover all the attributes used in BibXMLs, from my experience in authoring and using them as references.

Many attributes from RFC XML v3 are not meant to be used in BibXML (remember, BibXML is a **subset** of RFC XML v3 `<front>`), those attributes can be for publication/production usage.

**Comment by CAMOBAP** [comment]
Thanks for update, I will double-check this repo against last changes in ralaton-bib, and close this one

**Comment by strogonoff** [comment]
BibXML indexer is ready for this lib’s integration.

All that’s required is that the lib can take a file or a string like this:

http://34.229.41.119:8000/api/v1/ref/nist/NIST_FIPS_8-6/?format=bibxml

And return a structure like this (as a native Python dict, not as JSON):

http://34.229.41.119:8000/api/v1/ref/nist/NIST_FIPS_8-6/?format=relaton

Currently, the second structure (Relaton) is provided in `relaton-data-nist` repository, but we want to stop relying on those Relaton repositories and generate our own from BibXML.

**Comment by CAMOBAP** [comment]
@strogonoff ticket above will be addressed in scope of #6 (because it depends on dict creation)

In scope of this one few changes are missing:
 - https://github.com/relaton/relaton-bib/commit/dc67508e14537aef748bf06a6e2b3ee52f80caf0
 - https://github.com/relaton/relaton-bib/commit/1dbd64b97871ad5ed33e7fc94d3215a5cd1e4116
 - https://github.com/relaton/relaton-bib/commit/a8c2b03904f81d26440045a26df9047a6e968ac8
 - https://github.com/relaton/relaton-bib/commit/986b13cc82fd3e4f9db531f80075e3734d1cd263
 - https://github.com/relaton/relaton-bib/commit/f03fedb2a3d64fed659ecefa6e791c28f7d3c6c4

**Comment by CAMOBAP** [comment]
commits above added to python version

**Comment by CAMOBAP** [comment]
Working on part for reading https://github.com/ietf-ribose/relaton-data-ieee/blob/main/data/IEC_62531.2012_REDLINE.yaml to BibliographicItem

We already have BibliographicItem to bibxml conversion

This part will be done in the scope of https://github.com/relaton/relaton-bib-py/issues/6 because it's intersect with YAML support
